import '../css/globals.css'
import '../css/mainpage.css'
import '../components/userlogo'
import Userlogo from "@/components/userlogo";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({ children }) {
  const isAuthenticated = false; // Здесь нужно проверить авторизацию пользователя

  return (
      <div>
        <header>
          <nav className="navbar">
            <ul className="navbar__menu">
              <li className="navbar__item">
                <a href="/" className="navbar__link"><i data-feather="home"></i><span>Главная</span></a>
              </li>
              <li className="navbar__item">
                <a href="/about-us" className="navbar__link"><i data-feather="users"></i><span>О нас</span></a>
              </li>
              <li className="navbar__item">
                <a href="/courses" className="navbar__link"><i data-feather="folder"></i><span>Курсы</span></a>
              </li>
              <li className="navbar__item">
                <a href="/news" className="navbar__link"><i data-feather="archive"></i><span>Новости</span></a>
              </li>
              <li className="navbar__item">
                <a href="/teachers" className="navbar__link"><i data-feather="help-circle"></i><span>Преподаватели</span></a>
              </li>
              <li className="navbar__item">
                <a href="/contact" className="navbar__link"><i data-feather="settings"></i><span>Обратная связь</span></a>
              </li>
            </ul>
          </nav>
          <Userlogo />
        </header>

        <main>{children}</main>

        <footer>
          {/* Здесь разместите содержимое футера */}
        </footer>
      </div>
  );
};
